#
---
- name: Play with Squid
  hosts: squid
  become: yes
  become_method: sudo
  gather_facts: yes
  roles:
    - resolv.conf
    - common

  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes
