#
---
- name: Play with Squid
  hosts: squid
  become: yes
  become_method: sudo
  gather_facts: no
  roles:
   - common

  tasks:
    - name: Upgrade all packages
      yum:
       name: '*'
       state: latest
