#
---
#- name: Play with Squid
#  hosts: squid
#  become: yes
#  become_method: sudo
#  gather_facts: yes
#  roles:
#    - resolv.conf
#    - common
#
#  tasks:
#    - name: Update yum cache
#      yum:
#        update_cache: yes

#    - name: Print all available facts
#      ansible.builtin.debug:
#        var: ansible_facts

#- name: playbook for starting and enabling the NetworkManager
#  hosts: squid1.anysrv.local
#  tasks:
#    - name: start the service
#      service:
#        name: NetworkManager
#        state: started
#        enabled: true

- name: playbook for configuring second interface
  hosts: squid1.anysrv.local
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    - include_role:
        name: rhel-system-roles.network

    - name: Print all available facts
        ansible.builtin.debug:
          var: ansible_facts.target_mac


