- name: playbook for configuring second interface
  become: yes
  become_user: root
  hosts: squid4.anysrv.local
  tasks:
    - debug:
        msg: "{{ item.address[0] }}"
      with_items:
      - "{{ hostvars[inventory_hostname].net_connections }}"