- name: playbook for configuring second interface
  become: yes
  become_user: root
  hosts: squid4.anysrv.local
  tasks:
    - debug:
        msg: "{{ item.name }}"
      with_items: "{{ hostvars[inventory_hostname].network_connections }}"