- name: playbook for configuring second interface
  become: yes
  become_user: root
  hosts: squid4.anysrv.local
  tasks:
    - name: "register_network_connection"
      set_fact:
        network_connection:
          - name: "{{ item.name }}"
            type: ethernet
            mac: "{{ item.mac }}"
            interface_name: "{{ item.name }}"
            persistent_state: "{{ item.persistent_state }}"
            state: "{{ item.state }}"
            ip:
              auto6: no
              auto_gateway: "{{ item.ip.auto_gateway }}"
              address:
                - "{{ item.ip.address[0] }}"
      register: network_connection_item
      with_items: "{{ hostvars[inventory_hostname].net_connections }}"
      no_log: true

    - name: "register_network_connections"
      set_fact:
        network_connections: "{{ network_connection_item.results | map(attribute='ansible_facts.network_connection') | list }}"

    - name: "Run Network role"
      include_role:
        name: linux-system-roles.network

#    - debug:
#        msg:
#          - "{{ hostvars[inventory_hostname].network_connections }}"
#      with_items:
#        - "{{ hostvars[inventory_hostname].network_connections }}"
#  roles:
#    -    linux-system-roles.network