- name: playbook for configuring second interface
  become: yes
  become_user: root
  hosts: squid4.anysrv.local
  tasks:
    - set_fact:
        - network_connections:
          - name: "{{ item.name }}"
            type: ethernet
            mac: "{{ item.mac }}"
            interface_name: "{{ item.name }}"
            persistent_state: "{{ item.persistent_state }}"
            state: "{{ item.state }}"
            ip:
              auto6: no
              auto_gateway: "{{ item.ip.auto_gateway }}"
              address:
                - "{{ item.ip.address[0] }}"
        with_items: "{{ hostvars[inventory_hostname].net_connections }}"

    - debug:
        msg: "{{ hostvars[inventory_hostname].network_connections }}"
#      with_items:
#        - "{{ hostvars[inventory_hostname].network_connections }}"
#  roles:
#    -    linux-system-roles.network