- name: playbook for configuring second interface
  become: yes
  become_user: root
  hosts: squid4.anysrv.local
  task:
   - set_fact:
       network_connections:
         - name: "{{ item.name }}"
           type: ethernet
           mac: "{{ item.mac }}"
           interface_name: "{{ item.name }}"
           persistent_state: present
           state: up
           ip:
             auto6: no
             auto_gateway: no
             address:
               - "{{ item.address }}"
       with_items: "{{ hostvars[inventory_hostname].net_connections }}"
  roles:
    -    linux-system-roles.network