- name: playbook for configuring second interface
  hosts: squid4.anysrv.local
  vars:
    target_mac: "00:50:56:01:4e:d0"
    network_connection:
      -  name: static-network
         type: ethernet
         mac: “{{ target_mac }}”
         state: up
         ip :
           dhcp: no
           address:
             -  192.168.0.5/24
  roles:
    -    linux-system-roles.network