- name: playbook for configuring second interface
  become: yes
  become_user: root
  hosts: squid4.anysrv.local
  vars:
    target_mac: "00:50:56:01:4e:d0"
    network_provider: "initscripts"
    network_connection:
      -  name: ens256
         type: ethernet
         mac: 00:50:56:01:4e:d0
         interface_name: ens256
         persistent_state: present
         state: up
         ip :
           dhcp: no
           gateway4: 37.18.89.1
           address:
             -  37.18.89.83/24
  roles:
    -    linux-system-roles.network