- name: playbook for configuring second interface
  become: yes
  become_user: root
  hosts: squid4.anysrv.local

  vars:
    target_mac: "00:50:56:01:4e:d0"
    network_provider: "initscripts"
    network_connection:
      -  name: "ens256"
         type: ethernet
         mac: “{{ target_mac }}”
         state: up
         ip :
           dhcp: no
           address:
             -  192.168.0.5/24
  roles:
    -    linux-system-roles.network